spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/temp_db}
server.port=${SERVER_PORT:8081}
app.security.default-api-key=${SPRING_API_KEY:SUPER-SECRET-DEV-KEY-2552}
app.security.default-client-name=ui-dev-client
